### ISSUE TITLE
Confusion about variable elimination order for loop closure

### ISSUE THREAD

**Issue by zqsh** [borglab/gtsam#108]
I read isam2 paper. How to build ayes Tree for a large loop closure really confuses me? In the example shown in the paper, this is an evolution of the Bayes tree. When loop closure happens, there should be a factor between x24 and x16, and when we update Bayesian Net, the factor will become a directed line, and there should be a clique that contains x_24 and x_16. But we do not find any clique contains x_24 and x_16 in the Bayes Tree show in the figure. I fail to figure out how to build the red nodes, variable elimination order matters, Can someone give a clue? Where can I find how to build Bayes Tree with loop closure in the code?  
![image](https://user-images.githubusercontent.com/28699575/64396994-a1502280-d02d-11e9-9781-7a09890a2077.png)

**Comment by dellaert** [comment]
x16 is in a clique below the split. You can probably reconstruct what happened by re-eliminating the red states with order x16, x15, x17, x18, x19, x20, x21, x22, x23, x24, and doing a clique analysis on resulting Bayes net, refer to 2017 "Factor Graphs for Robot Perception".

For future reference, since this is neither a bug nor a feature request please post these type of questions to the Google group.
