### ISSUE TITLE
Fisheye calibration factor in Python

### ISSUE THREAD

**Issue by fsa4859** [borglab/gtsam#1600]
I am trying to solve for fisheye intrinsic calibration and I am using **gtsam.GeneralSFMFactor2Cal3Fisheye**. I added a prior on the first landmark and also a prior on the calibration and distortion coefficients. no matter what are the values, I am always obtaining the final calibration results as identity and all distortion coefficients as zero as shown below

![image](https://github.com/borglab/gtsam/assets/69100847/1e29c2f7-d4ec-4673-8864-d06d0eec18c4)

are there any problems in my approach leading to this and what could be a possible solution to estimate the intrinsics?

Thanks!

**Comment by varunagrawal** [comment]
@fsa4859 I recommend asking this on the Google Group since the discussion there will be more prompt and we cannot debug this without more information about your code and setup.

If the discussion yields the result that there indeed is a bug, you can re-open this issue with the new information and we'll gladly fix it.
