### ISSUE TITLE
Smartfactor body_P_sensor

### ISSUE THREAD

**Issue by dellaert** [borglab/gtsam#20]
Not respected: fix it.

**Comment by mikesheffler** [comment]
What's the deal with this? I see `body_P_sensor_` mentioned in the `unwhitenedError` method in `SmartFactorBase.h`, but I think that's it. Where is it missed?

**Comment by dellaert** [comment]
Needs a unit test whether if we pass `body_P_sensor`, it is actually used in projection factors and the like. It seems it is not, so I expect unit test to fail, and then we have to fix that :-)

**Comment by mikesheffler** [comment]
I swear I'm not trying to be dense, but is this not covered by

`TEST( SmartProjectionPoseFactor, smartFactorWithSensorBodyTransform )`

in `testSmartProjectionPoseFactor.cpp`?

I'm suddenly interested because I'm using `SmartProjectionPoseFactor<Cal3_S2>` with a `sensor_to_body` transform, and I'm having a hell of a time.

I'm sure I'm just putting some garbage data in somewhere, but I figure it's worth asking ... :grin:

**Comment by mikesheffler** [comment]
Ah. Did you have [this](https://bitbucket.org/gtborg/gtsam/issues/411/smartposeprojfactor-error-with-sensor) (issue number 41 from the bitbucket site) in mind? What kind of test did you need?

**Comment by dellaert** [comment]
Just a test that checks that the projections are being done correctly if the camera is offset. Including derivatives

**Comment by ProfFan** [comment]
Closed by #379, please reopen if not :)
