### ISSUE TITLE
Travis fails but shows success

### ISSUE THREAD

**Issue by dellaert** [borglab/gtsam#39]
As an example, [this run]( https://travis-ci.com/borglab/gtsam/jobs/204686142) did not run the tests but failed (why?, was just a warning), but still shows up as a success.

**Comment by dellaert** [comment]
Travis is awesome ! We'll get it right :-)

**Comment by jlblancoc** [comment]
Hmm... I think the point is that Travis build #5, [here](https://travis-ci.com/borglab/gtsam/builds/113966855), spans into the matrix of jobs we defined and only one of jobs failed, [this one, 5.2](https://travis-ci.com/borglab/gtsam/jobs/204686143)... in this case due to a timeout (50 minutes) :man_facepalming: 

Any of the admins, could try hitting the "retry" button of [job 5.2](https://travis-ci.com/borglab/gtsam/jobs/204686143), since sometimes build times differ depending on the load of the server. 

Anyhow, it seems we'll have to use Travis CI's "stages" to overcome the time limit (sigh)

**Comment by dellaert** [comment]
Fixed issues in pr  #45
