### ISSUE TITLE
unregistered class - derived class not registered or exported when use gtsam::Values and gtsam::NonLinearFactorGraph 

### ISSUE THREAD

**Issue by lacie-life** [borglab/gtsam#804]
## Description

I face error when use gtsam::Values and gtsam::NonLinearFactorGraph : "terminate called after throwing an instance of 'boost::archive::archive_exception'
  what():  unregistered class - derived class not registered or exported"

I exported with boost:

#include <gtsam/base/serializationTestHelpers.h>
#include <gtsam/nonlinear/NonlinearFactorGraph.h>
......

BOOST_CLASS_EXPORT_GUID(gtsam::NonlinearFactorGraph, "gtsamNonLinearFactorGraph");
BOOST_CLASS_EXPORT_GUID(gtsam::Values, "gtsamValues");
.....

## Environment

Ubuntu 20.04
IDE: CLion
Boots version: 1.71.0.0ubuntu2
My GTSAM library installed by Install GTSAM from Ubuntu PPA stable 4.x stable release

sudo add-apt-repository ppa:borglab/gtsam-release-4.0
sudo apt update 
sudo apt install libgtsam-dev libgtsam-unstable-dev

Any one have suggestion about this issuse?
Thanks for help!!

**Comment by jlblancoc** [comment]
Start from this [source code](https://github.com/borglab/gtsam/blob/develop/tests/testSerializationSLAM.cpp).

Make sure of adding boost macros for every single class and template instance you use in your program! It’s really hard to debug since boost error messages doesn’t help, but in the end it works 😉
