### ISSUE TITLE
Factors for motion-only bundle adjustment

### ISSUE THREAD

**Issue by JeffR1992** [borglab/gtsam#907]
## Feature

I've read a few VIO/VSLAM papers (e.g. ORB-SLAM 2 and VINS-Mono to name some well known implementations), that mention using "motion-only bundle adjustment" as part of their pipelines. This essentially optimizes the camera pose against assumed known landmark positions (i.e. triangulated landmark positions are kept constant during the optimization), and seems to produce better results than PnP (which uses only the previous and current frames with constant triangulated landmark positions), as it is able to take into account landmark data associations over more than 2 frames.

## Motivation

In order to speed up VIO/VSLAM pipelines, it would be great if there was a way for `gtsam` to include a factor that would allow users to perform motion-only BA (similar to the `EdgeStereoSE3ProjectXYZOnlyPose` and `EdgeSE3ProjectXYZOnlyPose` factors provided by `g2o`).

## Alternatives

As my VSLAM pipeline uses a stereo setup, I've tried using the standard `GenericStereoFactor` provided by `gtsam` with noise/uncertainty set to zero in the noise model, but this doesn't seem to produce any speed benefits. Are there alternatives to `GenericStereoFactor` that would allow me to perform motion-only BA? I've had a look at the `NonlinearEquality` class but it seemed like this might not be what I'm looking for.

**Comment by NickPerezCarletonUniversity** [comment]
@JeffR1992 did you end up figuring this out? :)

**Comment by JeffR1992** [comment]
Unfortunately I haven't had time to do this. However, after coming back to this having read a few more papers it sounds like motion-only BA is equivalent to structureless BA, in which case the paper titled "On-Manifold Preintegration for Real-Time
Visual-Inertial Odometry", which states that it uses "structureless vision factors", is useful to read. @dellaert  are these factors equivalent to the `SmartStereoProjectionPoseFactor` types in `gtsam_unstable/slam`, and if so would you advise I use these smart factors instead of going down the expression factor route?

**Comment by dellaert** [comment]
Sure. This is what several people do, although the students/postdocs doing it here at Georgia Tech have long since moved on :-)
Some more papers from those folks:

1. [Mining Structure Fragments for Smart Bundle Adjustment](http://www.cc.gatech.edu/~dellaert/pub/Carlone14bmvc.pdf), [Luca Carlone](http://www.lucacarlone.com/), [Pablo Fernández Alcantarilla](http://www.robesafe.com/personal/pablo.alcantarilla/index.html), Han-Pang Chiu, Zsolt Kira, and [Frank Dellaert](https://dellaert.github.io/), [British Machine Vision Conference (BMVC)](http://bmvc2014.cs.nott.ac.uk/), 2014
2. [Eliminating Conditionally Independent Sets in Factor Graphs: A Unifying Perspective based on Smart Factors](http://www.cc.gatech.edu/~dellaert/pub/Carlone14icra.pdf), [Luca Carlone](http://www.lucacarlone.com/), Zsolt Kira, [Chris Beall](http://borg.cc.gatech.edu/people/cbeall3), [Vadim Indelman](http://vindelman.technion.ac.il/), and [Frank Dellaert](https://dellaert.github.io/), [IEEE International Conference on Robotics and Automation (ICRA)](http://www.icra2011.org/), 2014
3. [Incremental Light Bundle Adjustment for Robotics Navigation](http://www.cc.gatech.edu/~dellaert/pub/Indelman13iros.pdf), [Vadim Indelman](http://vindelman.technion.ac.il/), Andrew Melim, and [Frank Dellaert](https://dellaert.github.io/), [IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS)](http://www.iros2010.org.tw/), 2013
4. [Probabilistic Analysis of Incremental Light Bundle Adjustment](http://www.cc.gatech.edu/~dellaert/pub/Indelman13worv.pdf), [Vadim Indelman](http://vindelman.technion.ac.il/), [Richard Roberts](http://www.cc.gatech.edu/~richard), and [Frank Dellaert](https://dellaert.github.io/), IEEE Workshop on Robot Vision (WoRV), 2013

See https://dellaert.github.io/publications/

**Comment by JeffR1992** [comment]
Thanks for the links to those papers, I've read (2) which was great, but I'll take a look at the others as well when I get some time.

Apologies if I didn't fully understand your previous reply @dellaert . When you said "although the students/postdocs doing it here at Georgia Tech have long since moved on", were you implying that the use of smart factors for motion-only/structureless BA with GTSAM is not regarded as a "best practice" anymore, and that there are better ways to perform this (e.g. expression factors that you mentioned originally)? Or are you saying that the students/postdocs that worked on smart factors for the GTSAM library have simply graduated or left the lab, but that smart factors are still the best way to go for motion-only/structureless BA? Thanks!

**Comment by dellaert** [comment]
Ha :-) The latter: the students/postdocs *literally* moved to other places. The ideas are still valid and are still bing actively used, e.g., @lucacarlone and his team have recently added new smart factor variants to deal with rolling shutter etc.

**Comment by JeffR1992** [comment]
Haha, thanks for clearing that up, I'll take a look at smart factors and see if I can get something to work. Thanks for your suggestions!

**Comment by dellaert** [comment]
OK, I will then close this issue for now.

**Comment by laxnpander** [comment]
@GabiShahmayster I have written a motion-only BA for my own framework. There are some custom types in this code snippet, but it should be straightforward to work out. I have another implementation in ceres, which does the same thing and the results are pretty the same. So it should be somewhat legit. This is for the monocular pinhole case only though.

```c
#include <gtsam/geometry/Point2.h>
#include <gtsam/geometry/Point3.h>
#include <gtsam/nonlinear/Values.h>
#include <gtsam/nonlinear/LevenbergMarquardtOptimizer.h>
#include <gtsam/inference/Symbol.h>

using namespace spear::gtsam::motion;

Problem::Problem()
{
  // Noise for 2D features is 1 px in x and y
  m_noise_fts  = ::gtsam::noiseModel::Isotropic::Sigma(2, 1.0);
  m_huber_loss = ::gtsam::noiseModel::Robust::Create(::gtsam::noiseModel::mEstimator::Huber::Create(1.345), m_noise_fts);

  // Noise for 3D pose
  Vector6d sigmas; sigmas << Vector3d(0.1,0.1,0.1), Vector3d(0.05,0.05,0.05);
  m_noise_pose = ::gtsam::noiseModel::Diagonal::Sigmas(sigmas);
}

spear::SE3r Problem::solve()
{
  std::cout << "Solving motion only problem..." << std::endl;
  ::gtsam::Values initial;
  initial.insert(::gtsam::Symbol('t', 0), m_twc);

  std::cout << "Initial error: " << m_graph.error(initial) << std::endl;
  ::gtsam::Values result = ::gtsam::LevenbergMarquardtOptimizer(m_graph, initial).optimize();
  std::cout << "Final error: " << m_graph.error(result) << std::endl;

  auto twc = result.at<::gtsam::Pose3>(::gtsam::Symbol('t', 0));

  return SE3r{twc.matrix()};
}

void Problem::setCamera(const std::shared_ptr<const Camera> &cam)
{
  // Currently only pinhole is supported
  auto pinhole = std::dynamic_pointer_cast<const Pinhole>(cam);

  // Initialise pose and calibration values + expressions
  m_twc  = ::gtsam::Pose3(pinhole->twc().matrix3x4());
  m_twc_ = std::make_unique<::gtsam::Expression<::gtsam::Pose3>>('t', 0);
  m_K    = ::gtsam::Cal3_S2(pinhole->fx(), pinhole->fy(), 0.0, pinhole->cx(), pinhole->cy());
  m_K_   = std::make_unique<::gtsam::Expression<::gtsam::Cal3_S2>>(m_K);

  m_graph.addExpressionFactor(*m_twc_, m_twc, m_noise_pose);
}

void Problem::addObservation(const Vector2d &kpt, const std::shared_ptr<const Landmark> &lm)
{
  Vector3d X((double)lm->x(), (double)lm->y(), (double)lm->z());
  ::gtsam::Expression<::gtsam::Point2> prediction_ = ::gtsam::uncalibrate(*m_K_, ::gtsam::project(::gtsam::transformTo(*m_twc_, X)));
  m_graph.addExpressionFactor(prediction_, kpt, m_huber_loss);
}
```

**Comment by nnop** [comment]
@JeffR1992 
Regarding the benefits of Motion-only BA over PnP(I think you mean DLT solver?), I think it's not because:
> it is able to take into account landmark data associations over more than 2 frames.
For they both take 3D points and 2D keypoints of current frame. But because the usage of nonlinear optimization over reprojection error.
